### ISSUE TITLE
decide on hosting infra setup (using railway for now)

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#103]
related to #6

**Comment by plor** [comment]
Requirements are needed for this decision, some I can think of right now:
- Multiple regions (to reside close to nodes)
- Docker and cluster management support (see #6) 
- Pricing (need constraints here)

**Comment by benedictvscriticus** [comment]
@plor lets go over this tomorrow during our sync

**Comment by benedictvscriticus** [comment]
- a version of AWS, GoogleCloud, Azure vs. the Digital Ocean of the world (Hetzner maybe)?
- we want to avoid vendor lock-in
- do we want to hedge by having different providers?
- Billing? crypto?

**Comment by benedictvscriticus** [comment]
@boucherbox name your startups

**Comment by benedictvscriticus** [comment]
Regions?

- US central
- Germany central
- Asia -> find out where in Asia - its big
- somewhere else? -> LatAm
- gateway should be close to the nodes
- research on POKT required
- check whether its on a UI
- follow up with Shane

**Comment by boucherbox** [comment]
web3 option for us

https://fluence.network/

**Comment by plor** [comment]
Decided on fly.io with #6
