### ISSUE TITLE
As a system, I want to be able to track usage per endpoint.

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#105]
Enables #44 
@plor defined the what below as follows:
> Usage will count down on the cache based on total relays. It will separately increment based on API key and chain (which will be pushed to postgres periodically. Each rate limiter will also decrement so a user can be cut off for a short time, while still having a total set of relays.

**Comment by plor** [comment]
Usage will count down on the cache based on total relays. It will separately increment based on API key and chain (which will be pushed to postgres periodically. Each rate limiter will also decrement so a user can be cut off for a short time, while still having a total set of relays.

**Comment by benedictvscriticus** [comment]
done on the usage side but not on the reporting side

**Comment by benedictvscriticus** [comment]
still have to figure out prometheus

**Comment by benedictvscriticus** [comment]
90% done - internet outage -ouch!

**Comment by benedictvscriticus** [comment]
all in the flow - just finalising it

**Comment by benedictvscriticus** [comment]
current focus of @plor . Prometheus is set up. May need to add more metrics after a walkthrough.
