### ISSUE TITLE
Write ERC-20 implementation

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#106]
Using standard ERC-20 contract, add one additional function:

`apply(amount, account)` where amount is the number of credits to apply and account is the ID provided by the UI for the tenant account. This id should be separate from any identifier for privacy reasons and new ones generated per apply if user prefers.

**Comment by plor** [comment]
I'm going to start a branch on this so I can work on it while making incremental progress on the caching layer. Discussed database changes with @memosys this morning that will block a couple of the changes on the postgres side, so putting another iron in the fire.

**Comment by boucherbox** [comment]
Product decision points:
1) what token allowed for payment?
2) what network(s)?
3) Name of the ERC20?
4) ???

@plor please add in points when appropriate

**Comment by boucherbox** [comment]
Size of token proposed: 1token = 1 million requests

**Comment by boucherbox** [comment]
Idea: only allow a single token for minting $PORT then leverage uniswap protocol for selling $PORT (eliminate the need for maintain price lists for $PORT)

**Comment by boucherbox** [comment]
Vote in https://discord.com/channels/1196976706381168701/1201593064091820203/1215357778353463376

For token name

**Comment by benedictvscriticus** [comment]
@plor is getting back at it. Is aiming at finishing a rough version today. He considers reaching out to another smart contract developer to get a second opinion.

**Comment by benedictvscriticus** [comment]
First pass is done. Tests need to be written and will inform revisions to the contract

**Comment by benedictvscriticus** [comment]
Testing (mint is fully tested). Passing tests now. Just have to continue with that. It would be nice to get a 2nd pair of eyes on it. It could be George or MrDeadcell
