### ISSUE TITLE
Build event listener to insert credits on ERC-20 `apply()` event

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#107]
Watch EVM logs on multiple deployed chains and on the event created in #106 perform an insert into the payment ledger. Include the tx hash in the reference field.

**Comment by plor** [comment]
It hasn't been decided which part of the stack this service lives.

**Comment by benedictvscriticus** [comment]
We must figure out a way to scale based on one database, as there will only be one postgres.

**Comment by benedictvscriticus** [comment]
@memosys is working on this as we speak.

**Comment by memosys** [comment]
Completed with #210
