### ISSUE TITLE
[EPIC-10] Business Development

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#109]
- [x] #134
- [x] #135
- [ ] #136
- [x] #137
- [x] #138
- [x] https://github.com/porters-xyz/product/issues/6

**Comment by boucherbox** [comment]
@benedictvscriticus can you drop the docs links here? the pitch deck etc

**Comment by benedictvscriticus** [comment]
@boucherbox here you go
