### ISSUE TITLE
Layout key format and data structure for redis datastore

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#11]
We need to have a clear structure for the redis store as populated by the postgres tables and for counters on request tracking and rate limiting.

- ACCOUNT:[id]
  - enabled
  - cached_remaining (sync with postgres)
  - relays_remaining (decr)
- APIKEY:[key]:meta
  - enabled
  - accountId
- APIKEY:[key]:[chainId]
  - relays (incr)
- CHAINS:[chainId]
  - weight

**Comment by plor** [comment]
Need to protect against collision and map from postgres to this structure.

**Comment by benedictvscriticus** [comment]
@plor is verifying whether the above schema covers everything. Let's make sure that we set up the usage first.

**Comment by benedictvscriticus** [comment]
on back burner as docker was prioritised, but almost done. Rate limiting structure on redis is yet to be defined.

**Comment by plor** [comment]
Each step of the lifecycle (being built as "plugins") will have it's own state management to redis. Each of these will relate to rules in the postgres database, which is read-only from the plugin. Current work is to avoid collisions as part of the "plugin" loading process. The first set of "plugins" are developed for porters, but it is being built so that they can be copied and modified to suit the needs of other organizations. Ideally, different versions of this gateway will only require a new main.go and a plugins package defining the lifecycle.

**Comment by benedictvscriticus** [comment]
Poor is working on the rule processors, which have the rights to write to redis. Main thing is to have the keys ready and implement safety mechanisms to avoid key collisions and accidental overwrites.

**Comment by benedictvscriticus** [comment]
Restructuring some of the gateway code

**Comment by benedictvscriticus** [comment]
The database is not yet sufficiently solidified.
