### ISSUE TITLE
Create favicon and brand assets and incorporate them into documentation app

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#111]

**Comment by boucherbox** [comment]
@vicosv has completed the favicon

@memosys needs to convert the favicon into an icon and add to repo

@benedictvscriticus to bring favicon into the documentation

**Comment by benedictvscriticus** [comment]
@memosys added favicon. @benedictvscriticus is taking over the remaining brand assets as much as possible.
