### ISSUE TITLE
Create rule schema that provides union of all rules for API key

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#114]
Rules need:
- [ ] Scoped at different levels (globally unique scope id)
- [ ] Searchable by API key (returns all scopes API key is tied to)
- [ ] Allows flexibility of rules (type, value, 1:n)
- [ ] Simple to avoid complexity at query level (both backend and gateway require query implementation)

**Comment by plor** [comment]
Let me know if we need further discussion on this, or if there is anything needing more clarity.

**Comment by plor** [comment]
This task might be slightly changed if API key is not the single thing that holds rules. We may need to abstract out slightly to support other use cases.

**Comment by memosys** [comment]
sub tasks need to be re-thought now that api key is just another rule; @plor

**Comment by benedictvscriticus** [comment]
Scope of the ticket has changed, but overall still applicable.
