### ISSUE TITLE
Prevent backend from crashing

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#115]
Errors on requests to javascript backend cause app to crash rather than returning a reasonable HTTP error (even just a 500 would be preferred to crashing). Crashing should only occur if there is something unrecoverable that requires the docker container to restart. Ideally this isn't something to worry about and we'll just be responding to 500 errors that exist.

**Comment by benedictvscriticus** [comment]
Might require to be watched in the future. A limitation is that it does not have except and capture. Fix for now, but a lil shaky. A global exception filter was previously enabled, but @memosys disabled.
