### ISSUE TITLE
Set up "sign-in with ethereum" and related session management

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#116]
Allow users to sign in with their Ethereum address, which will create them an account in our system where they can either create a new tenant or be added to an existing tenant. Sessions should be handled to follow the user stories #26  #55 #27 and #31

**Comment by benedictvscriticus** [comment]
The frontend and backend call have been written. Integration testing still required.

**Comment by benedictvscriticus** [comment]
@memosys explores something related to this. SIWE does not work well with next.js app router variant. We might want to switch to next.js base router or moving to pure react.

**Comment by memosys** [comment]
SIWE was implemented along with session cookie! 

there might be new tickets required 
1. to make it work as wrapper for Existing tenant key based system
2. Session Cookie based auth guard for each tenant/auth related end points

**Comment by benedictvscriticus** [comment]
https://github.com/porters-xyz/gateway-demo/issues/27

**Comment by benedictvscriticus** [comment]
It is there but not yet ready for prod.
