### ISSUE TITLE
Deploy on temporary shared environment

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#117]
Until we finalize our prod (and dev/qa) infrastructure in #103 , we want a temporary place for demoing and other QA type activities. This prevents issues with devs working only on local env.

**Comment by plor** [comment]
Let me know if you want to hand this off or have questions.

**Comment by benedictvscriticus** [comment]
It is not yet working due to redis networking and it is not yet auto-deploying.

**Comment by plor** [comment]
I updated gateway code to include username (I don't think this was issue) and log connection to redis. I'm removing the public networking for the databases and connecting on the internal network.

**Comment by plor** [comment]
Found this discussion of railway local dns not being fast enough https://www.answeroverflow.com/m/1194106303388327986, so need to add some retries in the connect. Will PR shortly.

**Comment by plor** [comment]
Working now, 
https://gateway-portal.up.railway.app/dashboard
https://gateway-demo-production.up.railway.app/
https://gateway-proxy.up.railway.app/

**Comment by plor** [comment]
I added healthcheck to be able to check whether redis is up (will respond "PONG") at `/health`
