### ISSUE TITLE
create pitch deck

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#118]
- [pitch deck](https://docs.google.com/presentation/d/1aTFTVUai0n1Xs6PeieY_odmiIGZFEZeeJk-ASQ6yfrs/edit?usp=drive_link)

**Comment by benedictvscriticus** [comment]
Designs given feedback to and now will be incorporated to slide deck master

**Comment by benedictvscriticus** [comment]
[2024-03-01_PORTERS_SLIDE_DECK.pdf](https://github.com/porters-xyz/gateway-demo/files/14455842/2024-03-01_PORTERS_SLIDE_DECK.pdf)

**Comment by benedictvscriticus** [comment]
Change raid guild logo colour

**Comment by plor** [comment]
What is the best way to provide feedback on this? I mostly have minor tweaks or questions.

**Comment by benedictvscriticus** [comment]
@plor I sent you an invite to the google slide deck, but you should be able to access this link too. https://docs.google.com/presentation/d/1aTFTVUai0n1Xs6PeieY_odmiIGZFEZeeJk-ASQ6yfrs/edit?usp=sharing

**Comment by boucherbox** [comment]
Shared with Plor's associated acct

**Comment by boucherbox** [comment]
@benedictvscriticus to incorporate comments and new version coming tomorrow
