### ISSUE TITLE
implement infrastructure for making use of an app stake to provision RPCs

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#121]

**Comment by plor** [comment]
We can do this against testnet stakes following this: https://github.com/pokt-network/gateway-server/blob/main/docs%2Fquick-onboarding-guide.md

Also got this from Blade for managing app stakes https://github.com/baaspoolsllc/pokt-stake-apps-script

**Comment by plor** [comment]
First step for this task is getting this working on testnet, but eventually we will mostly be building towards prod and use the app stakes we get from PNF.

**Comment by benedictvscriticus** [comment]
@plor is pinging blade about it. They released an update that fixes the issues @plor was having.

**Comment by benedictvscriticus** [comment]
more production app stakes, related #150

**Comment by benedictvscriticus** [comment]
@plor wants to call it done but hesitates
