### ISSUE TITLE
create wireframes and components for frontend app

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#128]
relates to
- #64 
- #62

**Comment by benedictvscriticus** [comment]
- usage data and insights available
    - for now will be slim, but will eventually get more
    - number of requests
    - success vs failure (percentage success or absolute numbers -> not sure yet)
    - hourly/daily/weekly/monthly? usage
    - balance or remainder for one app that was set by the admin

- warnings
    - warning for low balance
    - hitting the usage limit if hourly rate is close to be exceeded

This is what we envision for insights and usage for now. Can go over this at a later point @vicosv.

**Comment by boucherbox** [comment]
Vika Ben and Sass to meet 3/5 to run through content

Vika Sayo and Plor to meet tbd on UI/UX

**Comment by boucherbox** [comment]
Illustrations complete, wireframes moving along

CTA: @benedictvscriticus @plor @memosys @boucherbox give feedback on color, font, buttons and illustrations

**Comment by benedictvscriticus** [comment]
worked on dark mode, working now on settings page. Will be done end of this week, but needs a walkthrough with @plor and @memosys to check whether anything is missing.

**Comment by benedictvscriticus** [comment]
@vicosv posted an update to Discord and structuring the design files.

**Comment by benedictvscriticus** [comment]
ongoing collaboration between @memosys and @vicosv -> should remain in progress for now. @memosys was not expecting the level of detail and wanted guidance. Is asking for a toast and alert element.

**Comment by benedictvscriticus** [comment]
specify the UX of the search bar @vicosv
