### ISSUE TITLE
Run GatewayKit with testnet app stakes

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#150]
Using https://github.com/pokt-network/gateway-server/blob/main/docs%2Fquick-onboarding-guide.md#1-preparing-the-application-stakes add a GatewayKit node to the infra setup and route the proxy through this for testnet pokt relays.

**Comment by plor** [comment]
related to #121

**Comment by plor** [comment]
Ran into a few errors and reached out to Blade. They pushed a new release that should fix what I was running into, so going to try that.

**Comment by benedictvscriticus** [comment]
@plor got it working on fly.io now, but wants test it with all the other stuff.

**Comment by plor** [comment]
Going to spin off a new task for the proxy side (need to map subdomain to chainID in proxy routing)
