### ISSUE TITLE
Create async job queue on gateway.

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#151]
This allows the "plugins" to create tasks to eventually complete (things non-blocking to the servicing of relays). Example tasks to add here:
- cache stale checker (occasionally check postgres to avoid sync postgres calls)
- write "DEBIT" usage to postgres (hourly?)
- keep alive cache (update ttl on redis to keep pinned on usage)

**Comment by plor** [comment]
Working on this in parallel with app stake stuff. Making some progress, nothing specific to update yet.

**Comment by benedictvscriticus** [comment]
Check needs to run synchronously but anything else should be done async -> send to threads -> queued in a job queue

**Comment by benedictvscriticus** [comment]
@plor is currently working on this (fly.io was holding him back).

**Comment by benedictvscriticus** [comment]
Tests wrote, could be done, still need to be cleaned up.
