### ISSUE TITLE
Add product table to represent chains and other services

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#153]
Usage and price will reference specific products. Also app rules can be used to enable/disable particular products. This table will only be referred to by the relayLedger table as debits refer to which product is being used. Adding to this table can be done manually or we may add an admin interface for managing it.

**Comment by benedictvscriticus** [comment]
@vicosv here are some rules and information that needs to be shown

**Comment by plor** [comment]
I think this was recently pushed based on our conversation this week. Can you link the PR and note anything missing @memosys ?

**Comment by memosys** [comment]
This was handled in #156

**Comment by memosys** [comment]
Admin interface would be in bottom of priority ladder right now, tho but TBD!

**Comment by memosys** [comment]
By admin I mean gateway operators
