### ISSUE TITLE
deploy landing page

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#154]

**Comment by plor** [comment]
I'll be hooking up porters.xyz to railway prod env, so it should be able to handle the landing page when it is deployed.

**Comment by plor** [comment]
Set up:
- `www.porters.xyz`
- `staging.porters.xyz`
- `*.staging.porters.xyz`
I set up `www.porters.xyz` to point to empty deploy in the production environment that the landing page can be hooked up to when ready. Staging points to the portal front-end in staging environment and *.staging is to the staging proxy so we can start testing sub-domains for chainname.

**Comment by plor** [comment]
Does this look right @memosys?

**Comment by benedictvscriticus** [comment]
There is confusion whether it is a separate deploy or not

**Comment by benedictvscriticus** [comment]
@memosys is doing this today, i.e. deploying landing page in prod
