### ISSUE TITLE
implement swapping and redeeming UI

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#169]

**Comment by benedictvscriticus** [comment]
WIP, got UI done but isn't pushed yet

**Comment by memosys** [comment]
had a blocker with a good source of token list and addresses across chains!

Found a decent one for `Superchain` but not sure for Polygon, Arbitrum, Gnosis etc!

**Comment by benedictvscriticus** [comment]
We will go with OP for now regarding token metadata, but how do we go about price feeds? -> 0x.org? Let's keep it simple on our side and link to other places.

**Decision:**
- superchain solution found by @memosys 
- 0x.org for price feeds
- link out to other venues

**Comment by benedictvscriticus** [comment]
90% there, should be done today or tomorrow.

**Comment by benedictvscriticus** [comment]
Token is deployed to optimism by @plor .

**Comment by memosys** [comment]
Swap done, redeem tbd!

**Comment by memosys** [comment]
redeem done!

**Comment by memosys** [comment]
We should open a separate ticket for Improving UX of these widgets! 

Current focus was on getting them working!

**Comment by benedictvscriticus** [comment]
PR is waiting for @plor to review redeeming, he will close the ticket thereafter.
