### ISSUE TITLE
set up form for freemium request

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#171]
`<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfulvCOfLspV3RGFcGvNhoOKi5FXmViuu_vSJigsRhOIyxH-A/viewform?embedded=true" width="640" height="810" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>`

**Comment by boucherbox** [comment]
Process for giving out token is Ad-hoc ATM. Problematic long term

Need a better way to track the token distrobution

**Comment by boucherbox** [comment]
Starter Google Sheet
https://docs.google.com/spreadsheets/d/1GIsKPkjXrM1Lg6Jhn-85OpqIKUpl1-vzypmnrMOtVo4/edit?usp=sharing

**Comment by benedictvscriticus** [comment]
https://forms.gle/oPsJyTKgzJ2yFsVy5
