### ISSUE TITLE
implement freemium request form on frontend

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#172]
- [x] #267
- [x] #268

**Comment by benedictvscriticus** [comment]
Create link to airtable that is set up by @benedictvscriticus

**Comment by memosys** [comment]
> Create link to airtable that is set up by [@benedictvscriticus](https://github.com/benedictvscriticus)

ping

**Comment by benedictvscriticus** [comment]
`<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfulvCOfLspV3RGFcGvNhoOKi5FXmViuu_vSJigsRhOIyxH-A/viewform?embedded=true" width="640" height="810" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>`

Use this and make it work @memosys
