### ISSUE TITLE
Implement rate limit for app rule

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#181]

**Comment by plor** [comment]
I'm breaking these down so there are smaller chunks so that I don't hold on to commits for too long.

**Comment by memosys** [comment]
Pushed PR for frontend related to this!

**Comment by benedictvscriticus** [comment]
50% done, some refactoring to make others  go more quickly

**Comment by benedictvscriticus** [comment]
Back and forth between @memosys and @plor . Decision on rate limiting is done. @plor got a parser.
