### ISSUE TITLE
Prod deploy for fly.io

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#193]

**Comment by plor** [comment]
Deployed and running in similar configuration to staging. Need to set up DNS, look into deploying to other regions.

**Comment by plor** [comment]
DNS is hooked up, UI is having some issues with env (walletconnect)

**Comment by plor** [comment]
Need to tune the mem and cpu for each app. gateway kit ran out of memory, so needs increase.

**Comment by boucherbox** [comment]
App stakes are all on prod (any relay's through prod will incur the .85c/1M
