### ISSUE TITLE
Set up subdomain handler on proxy

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#195]
The proxy needs to accept all requests on `*.g.porters.xyz` (g for gateway). Then extract the * portion and lookup in product table to get the chainID. This is used to determine the url to proxy to on gatewaykit. Gatewaykit url will be http://gatewaykit.internal/relay/{poktChainID}

**Comment by benedictvscriticus** [comment]
almost done setting this up, related to #105
