### ISSUE TITLE
Add license to the repository

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#196]

**Comment by plor** [comment]
I'm thinking MIT should do fine. Open to other opinions.

**Comment by plor** [comment]
Also, maybe we should check what the preferred license setup is from the PNF perspective.

**Comment by memosys** [comment]
@boucherbox @benedictvscriticus sounds like your domain!!

> Also, maybe we should check what the preferred license setup is from the PNF perspective.

**Comment by plor** [comment]
I think they want us to avoid GPL-type licenses. I prefer MIT, but apache or BSD probably works too.

**Comment by benedictvscriticus** [comment]
I created a PR for the licence.
