### ISSUE TITLE
Create github actions for auto-deployment to fly.io on PR merge!

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#223]

**Comment by plor** [comment]
@memosys I assigned this to you and put in review since it is done and working. Just wanted to make sure you didn't have any last bits on this.

**Comment by memosys** [comment]
currently only handling `our apps` not `services` so do we want to automate that as well? thoughts on automating prod? but on `main` branch?

**Comment by plor** [comment]
ok, I'll move it back to in progress

**Comment by memosys** [comment]
> currently only handling `our apps` not `services` so do we want to automate that as well? thoughts on automating prod? but on `main` branch?

could you respond on expectation @plor

**Comment by plor** [comment]
I am ok with prod being manual as I don't think actions are high enough value there. Adding services would be my expectation, though since those are not code we manually edit (just updating version) I'm also ok leaving that out. Docs needs some love still.

**Comment by memosys** [comment]
We can close it then
