### ISSUE TITLE
Deploy payment contract on BASE

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#254]

**Comment by plor** [comment]
Deployed to 0x54D5F8A0E0F06991e63e46420Bcee1aF7D9fE944

**Comment by plor** [comment]
Need to set chainlink feed and price, also set up liquidity on uniswap.

**Comment by benedictvscriticus** [comment]
deployed but needs price and liquidity

**Comment by plor** [comment]
Set price and chainlink feed https://basescan.org/tx/0x4066135b0163f1dfc2b2a51beb01560080915d2955dc450a4f24ad2ff3fdcafd

Admin minted 1 billion PORTR for liquidity
https://basescan.org/tx/0x0f8461e12fd948535e30d3297f13a6d9def3f20db0319d16df2686eb2ef99686

**Comment by plor** [comment]
Set up liquidity pool https://basescan.org/tx/0xc5ea895da2a580e0b1d2f133efc3d8872fb90971a80216a4e34c632802530a13
