### ISSUE TITLE
Deploy payment contract on TAIKO

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#256]

**Comment by plor** [comment]
Chainlink isn't available on Taiko as far as I can tell, so all mints will have to be done by admin.

**Comment by plor** [comment]
https://taikoscan.io/tx/0xaa68a048fb4df7eeee11f3e00c5bf187e40dff6311b593d07fafeccfca1c744a
contract at 0x54D5F8A0E0F06991e63e46420Bcee1aF7D9fE944

**Comment by plor** [comment]
Pyth Chainlink adapter 0x0276c63a4e041d0dc4ee5b6c6c3b7a42d9f980fb

set feed and price https://taikoscan.io/tx/0x9f3f8d3cb1b91a130ebdcfdc2a83a95b77453caf8db895f4930f4ac8c6de1262

**Comment by plor** [comment]
needs to be added to frontend + backend for redeem

**Comment by plor** [comment]
for reference https://docs.pyth.network/price-feeds/migrate-an-app-to-pyth/chainlink
