### ISSUE TITLE
Implementing design review from @vicosv

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#257]

**Comment by memosys** [comment]
70% there

**Comment by memosys** [comment]
90% there

**Comment by memosys** [comment]
![Image](https://github.com/porters-xyz/gateway-demo/assets/82053242/9e2659a5-92b1-496f-9bed-eb06766278d6)

This is current ^




![Image](https://github.com/porters-xyz/gateway-demo/assets/82053242/385e819f-1b79-46b9-87a5-43780b99a2e3)

this blur part will eat from launch time!

**Comment by vicosv** [comment]
I agree that the landing page refinement is not a priority but a potential future enhancement.


Another design improvement I'd like to propose (also not top priority) is the unified style across the copiable elements, as well as one style for the 'copied' indication. I would stick to the style on the following screenshot. 

![Image](https://github.com/porters-xyz/gateway-demo/assets/130321827/08e9a57b-512d-40b6-83c4-019226106ce8)

this is what I'd like to be changed 

↓

![Image](https://github.com/porters-xyz/gateway-demo/assets/130321827/54fee3bf-bac6-4213-bef1-ee170e4e8321)
