### ISSUE TITLE
As a user, I want to be able to access a permissioned area of the Application by using SIWE.

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#27]
related to

- [x] #144

**Comment by boucherbox** [comment]
@memosys needs to discuss with @plor: how to manipulate the tenant from the user entity

**Comment by benedictvscriticus** [comment]
@memosys says its partially done. There is no global guard, but when you're signed in you can put in your details. Security testing is required.

You can create and see the apps.
