### ISSUE TITLE
[POR-205] Link from homepage to relevant URLs

### ISSUE THREAD

**Issue by memosys** [porters-xyz/gateway-demo#276]
- [x] #277
- [x] #278

<sub>[POR-205](https://linear.app/porters/issue/POR-205/link-from-homepage-to-relevant-urls)</sub>

**Comment by benedictvscriticus** [comment]
- top navigation bar missing
- coming soon needs to be replaced

**Comment by benedictvscriticus** [comment]
walk through the staging and close if satisfied
