### ISSUE TITLE
As a user, I want to be able to see a demonstration (not the app but a recording of someone using the app) of PORTERS.

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#28]

**Comment by benedictvscriticus** [comment]
@plor reads it more like a demo like a gif or arcade that one wants to be able to visit.

**Comment by boucherbox** [comment]
Create a video asset, host to youtube and link from app

**Comment by benedictvscriticus** [comment]
We should do this the next builder call (May 30th).
