### ISSUE TITLE
As a developer, I expect the PORTERS product to be based on the reference implementation.

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#30]

**Comment by plor** [comment]
My current proxy setup is to define packages for the functionality and a main.go that sets everything up. We may want to split these into separate repositories where the "library" is the reference implementation and then we move PORTERS specific things into a separate repo which also contains our infrastructure specific code. I imagine Dockerfile and docker-compose.yaml files being in the library, but fly.toml being specific to our decision to use fly.io.

**Comment by benedictvscriticus** [comment]
Created #236 in response. Is this done then?
