### ISSUE TITLE
As a dev using the ref. impl., I want to set restrictions and limitations for specific apps (including API keys if set up).

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#39]
- [x] #114

- Which apps can use the API keys
- Which chains should be accessible using the API keys
- How many requests (in total and per second/minute/hour/day) can be made using these API keys.
- more restrictions TBD

## Consists of the following rules:

- [x] #177 
- [x] #178 
- [x] #179 
- [x] #180 
- [x] #181

**Comment by benedictvscriticus** [comment]
Some seed rules have been done (very basic functionality). Database is structured accordingly.

**Comment by memosys** [comment]
same as #37

**Comment by benedictvscriticus** [comment]
endpoints are merged but unsure whether there are UI components for it yet. @memosys is working on components now

**Comment by benedictvscriticus** [comment]
added hooks and endpoints, as well as working on the ux to add and remove a rule

**Comment by benedictvscriticus** [comment]
@plor is doing the proxy side of things. @memosys what are format and value of the app rule?

**Comment by benedictvscriticus** [comment]
Pushed app rules implementation to proxy side

**Comment by memosys** [comment]
This can probably be closed now @benedictvscriticus
