### ISSUE TITLE
documentation setup

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#45]
the `setup` is done for a while.

is it okay to mark this one `done`? @plor

**Comment by plor** [comment]
Yeah, just to be consistent though, this was meant to be the deliverable that would be broken down into tasks. This comes from the POP doc.

**Comment by benedictvscriticus** [comment]
> Yeah, just to be consistent though, this was meant to be the deliverable that would be broken down into tasks. This comes from the POP doc.

@plor I misinterpreted this then. I thought it was about setting up docusaurus or similar, i.e. setting up the infra for publishing documentation.

**Comment by plor** [comment]
That's what it is about, my point was that this was created to keep track of the items in the POP. No task was created, so this took on the task features as well. It is fine if we use this as the task and call it done. My reason for pointing it out is to figure out if we need an issue type for the milestones.

**Comment by benedictvscriticus** [comment]
@plor I created a milestone here https://github.com/porters-xyz/gateway-demo/milestone/1 and added the tasks, stories, epics I thought belonged there. Happy to go over the list together.
