### ISSUE TITLE
As a user, I want to be able to access my tenant solely through my tenant identifier.

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#49]
@benedictvscriticus said:
> This user story should mirror the behaviour of IVPN.net for permissions of the main user and additional users they may add. Specific actions shall still require wallet message signing.

**Comment by benedictvscriticus** [comment]
next week demo

**Comment by plor** [comment]
@memosys just a reminder that we discussed this as a possible backup/recovery path.

**Comment by benedictvscriticus** [comment]
> @memosys just a reminder that we discussed this as a possible backup/recovery path.

We are building SIWE for now, but we can add another log-in path. Could be a recovery method on the tenant level. We want to be able to use the core infrastructure to expand and allow for self-administered tenant recovery, key rotation, permissions setting.
