### ISSUE TITLE
As a user, I want to be notified.

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#57]
This applies to the following cases:
- there is an issue with my app, account, and API key.
- there is suspicious activity
- billing

**Comment by benedictvscriticus** [comment]
- currently in-app notifications only
- we don't have an email fo users, thus, we cannot send them emails

**Comment by memosys** [comment]
pushing it to sprint 6; as its not a direct requirement for POP ( a/c to me) and has blockers in sprint 4,5 #44 

cc: @benedictvscriticus @plor @boucherbox

**Comment by memosys** [comment]
starting on this!

**Comment by memosys** [comment]
> This applies to the following cases:
> 
> * there is an issue with my app, account, and API key.
> * there is suspicious activity
> * billing

specifying these would be a great help!

My suggestions
1. I don't know when this could happen
2. Whats the criterion for flagging sus activity
3. At what point? utilising 50%, 75%,  100% of relay balance sounds alright to me?


thoughts @benedictvscriticus


@plor should these be frontend generated?

**Comment by plor** [comment]
Ideally this should be a backend service that the frontend checks as part of the use of the portal. This way we can move it to a service that runs when the user is not active and can send things like emails, discord messages, etc.

**Comment by benedictvscriticus** [comment]
1. I would say when a) an app is rate limit or b) 80% of relays are used
2. We cannot know so scrap it
3. I would suggest 80%

**Comment by memosys** [comment]
Frontend Done, Backend Mock API done; awaiting @plor to update proxy+prometheus with right metric

**Comment by memosys** [comment]
Done PR Open!
