### ISSUE TITLE
Decide on cluster tool for managing container scaling

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#6]
- [ ] choose provider
- [ ] choose how to manage our containers (some suggestions are Apache Tomcat and Kubernetes, dockerswarm)

**Comment by boucherbox** [comment]
kubernetes will be default unless strong opinions are found in RG etc

**Comment by plor** [comment]
Seems like there is a rough consensus that kubernetes is harder than it needs to be. Looking into fly.io as a possible alternate.

**Comment by benedictvscriticus** [comment]
Feedback from RaidGuild was that Kybernetes is hard core an alternative could be fly.io (USD 199/ month) + usage. Needs to be compared to AWS cost.

**Comment by benedictvscriticus** [comment]
look into fly.io a little bit more, as long as usage is steady should be a viable contender

**Comment by benedictvscriticus** [comment]
We decided that we will go with fly.io, setting up the following regions Singapore, Netherlands, Oregon.
