### ISSUE TITLE
implement menu designs on the frontend

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#63]

**Comment by vicosv** [comment]
I generally like the icon set we are using, but is there any alternative to this one that is more generic? like a gear icon @memosys 

![Image](https://github.com/porters-xyz/gateway-demo/assets/130321827/196b49fd-6b6b-4175-8e66-32907cb014fb)

**Comment by benedictvscriticus** [comment]
Let's switch to a gear icon for Settings
