### ISSUE TITLE
As a user, I want to see usage data and cost data for one specific app in the app detail page.

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#72]
- [x] https://github.com/porters-xyz/gateway-demo/issues/153

**Comment by benedictvscriticus** [comment]
Dependent on #83

**Comment by benedictvscriticus** [comment]
PR is coming

**Comment by benedictvscriticus** [comment]
Is blocked by @plor because data is not there yet

**Comment by plor** [comment]
#211 will open this up, I used "gateway" prefix for the prometheus rules related to relay usage

**Comment by benedictvscriticus** [comment]
@plor what do you mean by "open this up"?

**Comment by plor** [comment]
Unblock

**Comment by boucherbox** [comment]
Seen issues on testnet, hard to say if testnet or PORTERS is the culprit. @plor to try again on testnet, also document any issues with the testnet to communicate to the PNF. 

With app stakes might see problem resolved as well.

**Comment by boucherbox** [comment]
Data from Prometheus is not what @memosys needs. 

Solutions:
- help with Prometheus >>> ( community: https://community.fly.io/ )
- limit scope on displayed data
- switch data storage >> using postgres data (less granular and delayed)
