### ISSUE TITLE
As a user, I want to be able to access the billing section and download an invoice.

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#77]
- [ ] #167

**Comment by benedictvscriticus** [comment]
You can see the invoices but cannot download it.

**Comment by benedictvscriticus** [comment]
3pxl does not offer adding business data for the invoice issuer. Thus, we will have to go a custom route. We will take inspiration from the smart invoice implementation.

**Comment by memosys** [comment]
PR is open #235 

Needs enhancement- opened issue https://github.com/porters-xyz/product/issues/34
