### ISSUE TITLE
As a paying user, I want to receive refunds when closing my accounts to an EOA or contract address specified by me.

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#80]

**Comment by plor** [comment]
Is it ok handling this manually for now? I think the requirements for this need some discussion.

**Comment by benedictvscriticus** [comment]
@plor: Yes, in light of what we have agreed on regarding account deletion we can leave this as manual for now. Are manual reimbursements possible already?

**Comment by plor** [comment]
@benedictvscriticus We will need to figure out where the operations funds are held, then the process will be something like:

1) Close account so no more usage occurs
2) Wait for usage reconciliation to occur (unclear what cadence, but likely daily?)
3) Send funds to address (after verification of account ownership and closure)
4) Add a DEBIT to the PaymentLedger including refund tx to bring balance to 0

**Comment by benedictvscriticus** [comment]
@plor then let's go down that route. I think that's a pretty good spec for v. 1.0
