### ISSUE TITLE
finalize documentation

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#88]
Add documentation for all the features built to the documentation site. Get it ready for final publishing.

**Comment by benedictvscriticus** [comment]
@memosys should check why the documentation app is not deploying

**Comment by boucherbox** [comment]
Documentation is deployed, small issue with DNS (SSL certificate is not working) @plor debugging

**Comment by plor** [comment]
https://github.com/porters-xyz/gateway-demo/pull/310
