### ISSUE TITLE
As a frontend developer, I want to be able to use endpoints to support backend functionality on the frontend.

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#92]
- [x] #99

**Comment by benedictvscriticus** [comment]
- endpoints that were created:
     - creating tenant key
     - validating tenant key
     - get data for tenant
     - create API keys for a tenant
- more endpoints will be created
- Where are we documenting them? -> open question @memosys @plor

**Comment by benedictvscriticus** [comment]
let's us approach Georgeh to become our first alpha user

**Comment by benedictvscriticus** [comment]
rate limiting does not work

**Comment by memosys** [comment]
> rate limiting does not work

fixed it, it was typo on prod db!

**Comment by benedictvscriticus** [comment]
changed endpoints to be more authorisation fiendly
