### ISSUE TITLE
Set up pocket node for gateway kit

### ISSUE THREAD

**Issue by plor** [porters-xyz/gateway-demo#94]
Gateway kit requires a pocket node to be able to grab additional information for an app stake as well as other checks. Currently we are relying on an external node not meant for high volume usage. We should run our own node(s) so we aren't dependent on an external party and can scale as needed. Doing this for mainnet and testnet is important as well.

**Comment by boucherbox** [comment]
Message out to Nodies on altruist node and this Gateway Kit supporting node

**Comment by benedictvscriticus** [comment]
deferred to https://github.com/porters-xyz/product/issues/40
