### ISSUE TITLE
As a user, I want to be able to access all backend functionality through a portal, i.e. frontend.

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#97]
We want to connect the frontend and backend with this epic.

- [x] #128

**Comment by benedictvscriticus** [comment]
New endpoints added related to SIWE. Session strategy is still being figured out.

**Comment by boucherbox** [comment]
New endpoints added for Tenant and Apps

**Comment by boucherbox** [comment]
New endpoints for Apps, Org and enterprise

Not currently exposed

**Comment by benedictvscriticus** [comment]
more endpoints were created - similar update to last week

**Comment by benedictvscriticus** [comment]
getting the app endpoints more streamlined

**Comment by benedictvscriticus** [comment]
new endpoints were added (chains and utility endpoints) - same old. 🙃

**Comment by benedictvscriticus** [comment]
Created a batch update of endpoints for app rules.
