### ISSUE TITLE
create API specification

### ISSUE THREAD

**Issue by benedictvscriticus** [porters-xyz/gateway-demo#99]

**Comment by memosys** [comment]
could you elaborate this @benedictvscriticus 
cc: @plor

**Comment by boucherbox** [comment]
@memosys is looking into an auto-generation solution, if none exists then revert to manual entry

**Comment by benedictvscriticus** [comment]
@memosys found a solution.

**Comment by memosys** [comment]
live at [here](https://porters-backend-staging.fly.dev/specs#)

**Comment by memosys** [comment]
> live at [here](https://porters-backend-staging.fly.dev/specs#)

@plor not sure if its enough to close this issue, thoughts?

**Comment by plor** [comment]
A bit more information would be helpful. Does the library allow you to annotate the endpoints to describe stuff at all. Otherwise pretty clean.

**Comment by memosys** [comment]
> A bit more information would be helpful. Does the library allow you to annotate the endpoints to describe stuff at all. Otherwise pretty clean.

[Yeah](https://github.com/nestjs/nest/blob/master/sample/11-swagger/src/cats/cats.controller.ts)

We can probably enhance progressively and during documentation dive!
